### ISSUE TITLE
why make the `hosts` file only in the home directory?

### ISSUE THREAD

**Issue by procrypt** [truechain/truechain-consensus-core#11]
IMO user should be able to create `hosts` file anywhere not specifically in the `home` directory, unless there is a reason for doing it like this. 
I'll be very happy to send a PR for this as I already have one.

**Comment by arcolife** [comment]
+1 ..need a config file for a lot of tunables/config options. 
@samikshan is working on daemonizing this repo, so that the consensus is open to receiving transactions all the time and not commit suicide instead, based on the condition `if NUMQUEST messages are already processed`.

**Comment by procrypt** [comment]
@arcolife Cool I'll send it in while.

**Comment by arcolife** [comment]
covered in #57
