### ISSUE TITLE
Harden local folders permissions

### ISSUE THREAD

**Issue by blockauditech** [truechain/truechain-consensus-core#2]
**pbft-core/utils.go**
```
func MakeDirIfNot(dir string) {
	_, err := os.Stat(dir)
	if os.IsNotExist(err) {
		err := os.Mkdir(dir, 0777) // HERE
		CheckErr(err)
	}
}
```

0777 is too permissive. Should be 0700 or 0750 or even 0755, but not allow everyone to read/write/exec the new directory as this could enable any local users on the system to have full control over the new directories created.

**Comment by arcolife** [comment]
yes, thanks for pointing it out! This wasn't written well. /regret 
we'll fix it. /entente

**Comment by blockauditech** [comment]
Sure thing, good luck :-)

**Comment by arcolife** [comment]
https://github.com/truechain/truechain-consensus-core/commit/78cc25bdc206d7a10167623847972d287c865332#diff-ee59bf5531876270fc1480202b282377R75
