### ISSUE TITLE
use xgo for cross compile 

### ISSUE THREAD

**Issue by arcolife** [truechain/truechain-consensus-core#27]
Failed to produce `darwin` binary with `hmake build`, because a vendor dep uses `libsecp256k1` which in turn depends on `import "C"` in golang from under `secp256.go`

![photo6210981550418405391](https://user-images.githubusercontent.com/920859/42540732-873125f0-8454-11e8-8cf1-81ecdc14b88c.jpg)

screenshot courtesy: @hixichen 

So now, we have 2 options:
1. Cross compile from linux to darwin https://github.com/karalabe/xgo
2. Compile natively

**Comment by hixichen** [comment]
please check https://github.com/truechain/truechain-consensus-core/pull/62
