### ISSUE TITLE
gvt restore issue in hmake build (rebuilds entire dep on change in vendor/manifest)

### ISSUE THREAD

**Issue by arcolife** [truechain/truechain-consensus-core#39]
either sort this in `gvt restore` or shift to `go dep`. 

ref: https://gitter.im/truechain-net/engg-foss-global?at=5b45b9413d8f71623d6e9357

**Comment by hixichen** [comment]
Fixed manully but reorg the manifest.
https://github.com/truechain/truechain-consensus-core/pull/63

**Comment by arcolife** [comment]
@hixichen this issue is about "rebuilding entire deps structure" if just a couple changes are seen in vendor manifest. It's about not building the entire dep chain. I don't think it should be closed? 

gvt restore still functions the same way, doesn't it ?

**Comment by hixichen** [comment]
Not sure I fully understand your question. 
For dep management, you only need to restore them for the first time when you git clone the project.

It is developer's job to maintain the manifest file. 

why do we need to rebuild the entire deps structure?

**Comment by arcolife** [comment]
@hixichen here's the thing - we do it first time. Then we git pull in some changes after some time. So the vendor manifest changes.

So the next time we build with hmake, it rebuilds deps, because it watches over manifest. This build, triggers gvt restore.
