### ISSUE TITLE
done

### ISSUE THREAD

**Issue by coinnote** [truechain/truechain-consensus-core#4]
你们烧成灰大家都认识，彻彻底底的骗子项目

**Comment by coinnote** [comment]
http://sh.qihoo.com/pc/934c6380b6d45148f?sign=360_e39369d1#bd_comment  
微商导师变区块链专家，背景造假还上央视，这个项目套路有点深!

**Comment by coinnote** [comment]
下周我就去成方街和长安街举报你们，恶意利空割韭菜，恶意造势割韭菜

**Comment by coinnote** [comment]
http://new.qq.com/omn/20180410/20180410A0V7NJ.html 
林大亮辞去TrueChainCEO职务，曾被曝其背景造假

**Comment by coinnote** [comment]
更恶劣的，你们借着放利空打压币价自己吸筹，吸筹够了再放出一串串准备好的所谓利好，拉升币价，割韭菜自己获利。现在搞一个所谓空投，无形中又相当于增发了一个币，还要求提币到自己钱包锁仓一周，正好配合你们关门打狗，拉高出货。

**Comment by zhangjiannan** [comment]
Any further abusing threads will be reported and suspended.
